let PRODUCTS=[];let cart=JSON.parse(localStorage.getItem('sneaker-cart')||'[]');let activeCategory='all';
const euro=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n);const products=document.getElementById('products');
async function load(){try{const r=await fetch('products.json');const data=await r.json();PRODUCTS=data.products;render()}catch(e){products.innerHTML='<p>Produktkatalog konnte nicht geladen werden.</p>'}}
function render(){const q=(document.getElementById('search').value||'').toLowerCase();let list=PRODUCTS.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&(p.name+' '+p.description+' '+p.category).toLowerCase().includes(q));products.innerHTML=list.map(p=>`<article class="card"><button class="productlink" onclick="details('${p.id}')"><div class="pic">${p.image?`<img src="${p.image}" alt="${p.name}" onerror="this.remove();this.parentElement.classList.add('fallback')">`:''}<span>${p.name.split(' ')[0].toUpperCase()}</span></div></button><div class="info"><p class="tag">${p.category.toUpperCase()}</p><h3>${p.name}</h3><p>${p.description}</p><span class="price">${euro(p.price)}</span><button class="add" onclick="add('${p.id}')">ADD +</button></div></article>`).join('')||'<p class="empty">Keine Produkte gefunden.</p>'}
function details(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;document.getElementById('modalContent').innerHTML=`<div class="detail"><div class="detailpic">${p.image?`<img src="${p.image}" alt="${p.name}" onerror="this.style.display='none'">`:''}<span>${p.name.split(' ')[0].toUpperCase()}</span></div><div><p class="eyebrow">${p.category.toUpperCase()}</p><h2>${p.name}</h2><p>${p.description}</p><strong class="detailprice">${euro(p.price)}</strong><label>Größe<select id="size">${p.sizes.map(s=>`<option>${s}</option>`).join('')}</select></label><button class="btn" onclick="add('${p.id}');closeModal()">IN DEN WARENKORB</button></div></div>`;document.getElementById('modal').classList.add('show')}
function closeModal(){document.getElementById('modal').classList.remove('show')}function add(id){const x=cart.find(i=>i.id===id);x?x.qty++:cart.push({id,qty:1});save();openCart()}function save(){localStorage.setItem('sneaker-cart',JSON.stringify(cart));renderCart()}
function renderCart(){document.getElementById('cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0);document.getElementById('cartItems').innerHTML=cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);return p?`<div class="line"><span>${p.name} × ${x.qty}</span><b>${euro(p.price*x.qty)}</b></div>`:''}).join('')||'<p class="empty">Dein Warenkorb ist leer.</p>';document.getElementById('total').textContent=euro(cart.reduce((a,x)=>{const p=PRODUCTS.find(y=>y.id===x.id);return a+(p?p.price*x.qty:0)},0))}
function openCart(){document.getElementById('drawer').classList.add('open')}document.getElementById('cartOpen').onclick=openCart;document.getElementById('cartClose').onclick=()=>document.getElementById('drawer').classList.remove('open');document.getElementById('modalClose').onclick=closeModal;document.getElementById('modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.getElementById('search').oninput=render;document.querySelectorAll('[data-category]').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()});document.getElementById('checkout').onclick=()=>alert('Checkout ist vorbereitet. Zahlungsanbieter können hier angeschlossen werden.');
load();renderCart();
